on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: check

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: release
          install-r: false
          # use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-universe-org/build-and-check@master
        with:
          cranlikerepo: '"https://pik-piam.r-universe.dev"'

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
        
      - name: Validation key 
        run: if(!lucode2:::validkey()$valid) stop("Invalid build key!")
        shell: Rscript {0}
        
