on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: check

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: release
          install-r: false
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Use pik-piam r-universe
        shell: bash
        run: |
          echo "::group::Use PIK RSE server"
          echo 'options(repos = c(universe = "https://pik-piam.r-universe.dev", CRAN = "https://cloud.r-project.org"))' > .Rprofile
          echo "::endgroup::"

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Run tests
        run: devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}

      - name: Validation key 
        run: if(!lucode2:::validkey()$valid) stop("Invalid build key!")
        shell: Rscript {0}
